"""added_difficulty_and_caching

Revision ID: 1319f13cae3e
Revises: fd15530783d7
Create Date: 2026-05-02 15:37:47.695118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1319f13cae3e'
down_revision: Union[str, Sequence[str], None] = 'fd15530783d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('difficulty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outputs', 'difficulty')
    # ### end Alembic commands ###
